"""Tools for PMAdvisorAgent — project memory and pipeline artifact readers."""

from __future__ import annotations

import json
from typing import Any

from langchain_core.tools import BaseTool, StructuredTool

from forge.core.state import ProjectState


def _tool_get_solution_summary(state: ProjectState) -> str:
    """Return ProblemSolver solution summary for PM review."""
    solution = state.get("last_solution") or {}
    if not solution:
        return "（暂无 ProblemSolver 方案输出）"

    rec_id = solution.get("recommended_solution_id", "")
    rec = next(
        (s for s in solution.get("solutions", []) if s.get("id") == rec_id),
        solution.get("solutions", [{}])[0] if solution.get("solutions") else {},
    )
    payload = {
        "problem_analysis": solution.get("problem_analysis", ""),
        "root_causes": solution.get("root_causes", []),
        "recommended_solution_id": rec_id,
        "recommended_title": rec.get("title", ""),
        "recommended_description": rec.get("description", ""),
        "next_actions": solution.get("next_actions", []),
        "dengbao_considerations": solution.get("dengbao_considerations", ""),
        "itil_considerations": solution.get("itil_considerations", ""),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _tool_get_compliance_summary(state: ProjectState) -> str:
    """Return Compliance check summary with gaps and recommendations."""
    compliance = state.get("last_compliance_result") or {}
    if not compliance:
        return "（暂无 Compliance 检查结果）"

    payload = {
        "compliance_status": compliance.get("compliance_status", compliance.get("overall_status")),
        "risk_level": compliance.get("risk_level", "unknown"),
        "missing_items": compliance.get("missing_items", [])[:15],
        "recommendations": compliance.get("recommendations", [])[:10],
        "next_action": compliance.get("next_action", ""),
        "module_scores": [
            {
                "module": m.get("module_name", m.get("module")),
                "status": m.get("status"),
                "score": m.get("score"),
            }
            for m in compliance.get("results", [])
        ],
        "compliance_retry_count": state.get("compliance_retry_count", 0),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _tool_get_documents_index(state: ProjectState) -> str:
    """Return index of documents generated by DocumentAgent."""
    docs = state.get("generated_documents", [])
    if not docs:
        return "（未生成项目资料 — 可能因合规未达标或流程跳过）"

    index = [
        {
            "doc_id": d.get("doc_id"),
            "doc_type": d.get("doc_type"),
            "title": d.get("title"),
            "preview": (d.get("content", "") or "")[:200],
        }
        for d in docs
    ]
    return json.dumps(index, ensure_ascii=False, indent=2)


def _tool_get_project_memory(state: ProjectState) -> str:
    """Return knowledge base entries and agent conversation timeline."""
    kb = state.get("knowledge_base", [])
    history = state.get("conversation_history", [])

    kb_summary = [
        {
            "category": e.get("category"),
            "content": (e.get("content", "") or "")[:300],
            "tags": e.get("tags", []),
        }
        for e in kb[-8:]
    ]
    timeline = [
        {
            "agent": h.get("agent"),
            "event": h.get("event"),
            "summary": h.get("summary"),
        }
        for h in history[-12:]
    ]
    payload = {"knowledge_base_recent": kb_summary, "conversation_timeline": timeline}
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _tool_get_project_context(state: ProjectState) -> str:
    """Return project phase, WBS snapshot, and open pending tasks."""
    pending = [
        {
            "title": t.get("title"),
            "assigned_to": t.get("assigned_to"),
            "priority": t.get("priority"),
            "status": t.get("status"),
        }
        for t in state.get("pending_tasks", [])
        if t.get("status") == "open"
    ]
    payload = {
        "project_id": state.get("project_id"),
        "current_phase": state.get("current_phase"),
        "enabled_modules": state.get("enabled_modules", []),
        "active_workflow": state.get("active_workflow"),
        "wbs_keys": list((state.get("wbs") or {}).keys())[:10],
        "open_pending_tasks": pending,
        "rule_pack": state.get("rule_pack"),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def build_pm_advisor_tools(state: ProjectState) -> list[BaseTool]:
    """Build PMAdvisor tools bound to the current project state."""

    def solution_summary() -> str:
        return _tool_get_solution_summary(state)

    def compliance_summary() -> str:
        return _tool_get_compliance_summary(state)

    def documents_index() -> str:
        return _tool_get_documents_index(state)

    def project_memory() -> str:
        return _tool_get_project_memory(state)

    def project_context() -> str:
        return _tool_get_project_context(state)

    return [
        StructuredTool.from_function(
            func=solution_summary,
            name="get_solution_summary",
            description="获取 ProblemSolver 方案摘要（分析、根因、推荐方案、下一步）",
        ),
        StructuredTool.from_function(
            func=compliance_summary,
            name="get_compliance_summary",
            description="获取 Compliance 合规状态、缺口、整改建议与模块得分",
        ),
        StructuredTool.from_function(
            func=documents_index,
            name="get_documents_index",
            description="获取 DocumentAgent 生成的资料清单与预览",
        ),
        StructuredTool.from_function(
            func=project_memory,
            name="get_project_memory",
            description="读取项目知识库与 Agent 交互时间线（项目记忆）",
        ),
        StructuredTool.from_function(
            func=project_context,
            name="get_project_context",
            description="获取项目阶段、WBS、待办任务与 Rule Pack 配置",
        ),
    ]


def run_pm_advisor_research(state: ProjectState, user_question: str) -> str:
    """Offline fallback: run all PM advisor tools and concatenate results."""
    sections = [
        ("## 方案摘要", _tool_get_solution_summary(state)),
        ("## 合规摘要", _tool_get_compliance_summary(state)),
        ("## 资料清单", _tool_get_documents_index(state)),
        ("## 项目记忆", _tool_get_project_memory(state)),
        ("## 项目上下文", _tool_get_project_context(state)),
        ("## 用户问题", user_question),
    ]
    return "\n\n".join(f"{title}\n{body}" for title, body in sections)
