from forge.prompts.compliance.prompts import (
    COMPLIANCE_REACT_TASK,
    COMPLIANCE_STRUCTURED_PROMPT,
    COMPLIANCE_SYSTEM,
)

__all__ = ["COMPLIANCE_REACT_TASK", "COMPLIANCE_STRUCTURED_PROMPT", "COMPLIANCE_SYSTEM"]
