"""Agent prompt templates — prefer ``prompts/<agent>/`` package paths."""

from forge.prompts.compliance import COMPLIANCE_REACT_TASK, COMPLIANCE_STRUCTURED_PROMPT, COMPLIANCE_SYSTEM
from forge.prompts.document import DOCUMENT_SYSTEM
from forge.prompts.operations import OPERATIONS_REACT_TASK, OPERATIONS_STRUCTURED_PROMPT, OPERATIONS_SYSTEM
from forge.prompts.pm_advisor import PM_ADVISOR_REACT_TASK, PM_ADVISOR_STRUCTURED_PROMPT, PM_ADVISOR_SYSTEM
from forge.prompts.problem_solver import (
    PROBLEM_SOLVER_REACT_TASK,
    PROBLEM_SOLVER_STRUCTURED_PROMPT,
    PROBLEM_SOLVER_SYSTEM,
)
from forge.prompts.security import SECURITY_REACT_TASK, SECURITY_STRUCTURED_PROMPT, SECURITY_SYSTEM

__all__ = [
    "COMPLIANCE_REACT_TASK",
    "COMPLIANCE_STRUCTURED_PROMPT",
    "COMPLIANCE_SYSTEM",
    "DOCUMENT_SYSTEM",
    "OPERATIONS_REACT_TASK",
    "OPERATIONS_STRUCTURED_PROMPT",
    "OPERATIONS_SYSTEM",
    "PM_ADVISOR_REACT_TASK",
    "PM_ADVISOR_STRUCTURED_PROMPT",
    "PM_ADVISOR_SYSTEM",
    "SECURITY_REACT_TASK",
    "SECURITY_STRUCTURED_PROMPT",
    "SECURITY_SYSTEM",
    "PROBLEM_SOLVER_REACT_TASK",
    "PROBLEM_SOLVER_STRUCTURED_PROMPT",
    "PROBLEM_SOLVER_SYSTEM",
]
